name: "Add jar to Release"
description: "Add a jar file to a Github Release"
inputs:
  jar-path:
    required: true
    description: "Path of the jar file"
runs:
  using: "composite"
  steps:
    - name: Upload Release Asset
      run: |
        cd ${{github.workspace}}
        gh release upload ${{github.event.release.tag_name}} ${{ inputs.jar-path }}
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
